
import { MapArea } from './types';

export const INDEX_IMAGE_URL = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhte70ALtQcyrnaRRftms4GFuU5_yUtYjLCwF7EqF_EqH8wPS-Sv-MKHGXJ9njCHN4xZLOvIiQAMmK8V8ayZISmkUzTml07g8DYWimAu92T61PVaPGQAOUXnbVWkf-Fc-nzBeAUhXJCVpcp/s1600/Index+50+000+-+25+juin+2016.jpg";

const p = (c: string) => c.split(',').map(Number);

// Regions Constants
const R_TTA = "طنجة - تطوان - الحسيمة";
const R_ORI = "الشرق";
const R_RSK = "الرباط - سلا - القنيطرة";
const R_FM = "فاس - مكناس";
const R_BK = "بني ملال - خنيفرة";
const R_CS = "الدار البيضاء - سطات";
const R_MA = "مراكش - آسفي";
const R_DT = "درعة - تافيلالت";
const R_SM = "سوس - ماسة";

export const MAP_DATA: MapArea[] = ([
    // Tanger-Tetouan-Al Hoceima
    { id: "1", name: "Tanger", nameAr: "طنجة", shape: "rect", coords: p("391,10,411,34"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAVTE4ejZ4OTNRVXc/view?usp=sharing", title: "1 : Tanger", region: R_TTA, province: "إقليم الفحص-أنجرة" },
    { id: "2", name: "Ksar Es Srhir", nameAr: "القصر الصغير", shape: "rect", coords: p("412,10,431,34"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATzVCYjlVNDhRZzA/view?usp=sharing", title: "2 : Ksar Es Srhir", region: R_TTA, province: "إقليم الفحص-أنجرة" },
    { id: "3", name: "Sebta ( Ceuta )", nameAr: "سبتة", shape: "rect", coords: p("432,8,451,33"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAa1dxb2FtbW5jdHM/view?usp=sharing", title: "3 : Sebta ( Ceuta )", region: R_TTA, province: "إقليم تطوان" },
    { id: "4", name: "El Manzla", nameAr: "المنزلة", shape: "rect", coords: p("391,35,412,58"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALTVFSkVJN0VRbms/view?usp=sharing", title: "4 : El Manzla", region: R_TTA, province: "إقليم الفحص-أنجرة" },
    { id: "5", name: "Melloussa", nameAr: "ملوسة", shape: "rect", coords: p("412,35,431,59"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAS19mUDFrTHYwNmM/view?usp=sharing", title: "5 : Melloussa", region: R_TTA, province: "إقليم الفحص-أنجرة" },
    { id: "6", name: "Tetouan", nameAr: "تطوان", shape: "rect", coords: p("432,34,452,58"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWVBMYW1IVFNfRjA/view?usp=sharing", title: "6 : Tetouan", region: R_TTA, province: "إقليم تطوان" },
    { id: "7", name: "Ras Mazari", nameAr: "رأس مزاري", shape: "rect", coords: p("452,33,472,58"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALUUzNGJJako3Umc/view?usp=sharing", title: "7 : Ras Mazari", region: R_TTA, province: "إقليم تطوان" },
    { id: "8", name: "Asilah", nameAr: "أصيلة", shape: "rect", coords: p("372,59,392,84"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAUVQxUFlSeXV3d0k/view?usp=sharing", title: "8 : Asilah", region: R_TTA, province: "إقليم تطوان" },
    { id: "9", name: "Arba Ayacha", nameAr: "أربعاء عياشة", shape: "rect", coords: p("393,58,412,84"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAUDFMQ3Z1WjFlU0k/view?usp=sharing", title: "9 : Arba Ayacha", region: R_TTA, province: "إقليم تطوان" },
    { id: "10", name: "Souk Khemis Des Beni Arouss", nameAr: "خميس بني عروس", shape: "rect", coords: p("413,59,432,83"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAX0tYLU1lV1YzSFU/view?usp=sharing", title: "10 : Souk Khemis Des Beni Arouss", region: R_TTA, province: "إقليم تطوان" },
    { id: "11", name: "Souk Larba Beni Hessane", nameAr: "أربعاء بني حسان", shape: "rect", coords: p("433,59,452,83"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWmhUcmMxQUh6alU/view?usp=sharing", title: "11 : Souk Larba Beni Hessane", region: R_TTA, province: "إقليم تطوان" },
    { id: "12", name: "Talembote", nameAr: "تلمبوط", shape: "rect", coords: p("452,58,472,82"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAN0ZPRFJubkttX3M/view?usp=sharing", title: "12 : Talembote", region: R_TTA, province: "إقليم تطوان" },
    { id: "13", name: "Bou Ahmed", nameAr: "بو أحمد", shape: "rect", coords: p("473,57,494,82"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAVEpmN3phdWNfd28/view?usp=sharing", title: "13 : Bou Ahmed", region: R_TTA, province: "إقليم تطوان" },
    { id: "14", name: "Melilla", nameAr: "مليلية", shape: "rect", coords: p("618,51,641,76"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAamt6UnREYmhJSm8/view?usp=sharing", title: "14 : Melilla", region: R_TTA, province: "إقليم الحسيمة" },
    { id: "15", name: "Larache", nameAr: "العرائش", shape: "rect", coords: p("372,85,393,108"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASm9FNFMxSXVXcFE/view?usp=sharing", title: "15 : Larache", region: R_TTA, province: "إقليم العرائش" },
    { id: "16", name: "El Ksar El Kbir", nameAr: "القصر الكبير", shape: "rect", coords: p("394,84,412,108"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAb1JKenU0VVUxOWc/view?usp=sharing", title: "16 : El Ksar El Kbir", region: R_TTA, province: "إقليم العرائش" },
    { id: "17", name: "Souk El Kolla", nameAr: "سوق القلة", shape: "rect", coords: p("413,84,433,108"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARDlwMmZ6cFVTYjg/view?usp=sharing", title: "17 : Souk El Kolla", region: R_TTA, province: "إقليم العرائش" },
    { id: "18", name: "Chefchaouen", nameAr: "شفشاون", shape: "rect", coords: p("433,83,452,107"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASWhfSF9HcG9KWFE/view?usp=sharing", title: "18 : Chefchaouen", region: R_TTA, province: "إقليم شفشاون" },
    { id: "19", name: "Bab Taza", nameAr: "باب تازة", shape: "rect", coords: p("453,83,473,106"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZkowODR5cmJFSFk/view?usp=sharing", title: "19 : Bab Taza", region: R_TTA, province: "إقليم شفشاون" },
    { id: "20", name: "Bab Berret", nameAr: "باب برد", shape: "rect", coords: p("474,83,494,106"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAYmt6RG1NeFYyQkE/view?usp=sharing", title: "20 : Bab Berret", region: R_TTA, province: "إقليم شفشاون" },
    { id: "21", name: "El Jabha", nameAr: "الجبهة", shape: "rect", coords: p("495,82,514,105"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbmhzQVhFQnZaM1E/view?usp=sharing", title: "21 : El Jabha", region: R_TTA, province: "إقليم شفشاون" },
    { id: "22", name: "Beni Boufrah", nameAr: "بني بوفراح", shape: "rect", coords: p("514,79,534,104"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQmtiNkNCb01GbTA/view?usp=sharing", title: "22 : Beni Boufrah", region: R_TTA, province: "إقليم الحسيمة" },
    { id: "23", name: "Rouadi", nameAr: "رؤادي", shape: "rect", coords: p("535,78,554,104"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASUtJdGdHZ3p3eG8/view?usp=sharing", title: "23 : Rouadi", region: R_TTA, province: "إقليم الحسيمة" },
    { id: "23 bis", name: "Al Hoceima", nameAr: "الحسيمة", shape: "rect", coords: p("555,77,574,103"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARVFlZi1KNTJQUEE/view?usp=sharing", title: "23 bis : Al Hoceima", region: R_TTA, province: "إقليم الحسيمة" },
    { id: "24", name: "Boudinar", nameAr: "بودينار", shape: "rect", coords: p("574,74,595,102"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWnRUaTl1TTRZYU0/view?usp=sharing", title: "24 : Boudinar", region: R_TTA, province: "إقليم الحسيمة" },
    { id: "25", name: "Kebdani", nameAr: "كبداني", shape: "rect", coords: p("596,78,615,101"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAc2stQUhtNXJ2Q1U/view?usp=sharing", title: "25 : Kebdani", region: R_TTA, province: "إقليم الحسيمة" },
    
    // Oriental
    { id: "26", name: "Zeghanghane", nameAr: "أزغنغان", shape: "rect", coords: p("615,76,635,101"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARXpjaFctd0N3Mkk/view?usp=sharing", title: "26 : Zeghanghane", region: R_ORI, province: "إقليم الناظور" },
    { id: "27", name: "Nador", nameAr: "الناظور", shape: "rect", coords: p("636,76,655,99"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAb08xOTJjeXZYNnc/view?usp=sharing", title: "27 : Nador", region: R_ORI, province: "إقليم الناظور" },
    { id: "28", name: "Kariat Arekmam", nameAr: "قرية أركمان", shape: "rect", coords: p("655,74,676,100"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASHBoNUNhemtfWjA/view?usp=sharing", title: "28 : Kariat Arekmam", region: R_ORI, province: "إقليم الناظور" },
    { id: "29", name: "Les Triffa", nameAr: "تريفة", shape: "rect", coords: p("676,72,694,97"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARjJWRTdWZFhMdWM/view?usp=sharing", title: "29 : Les Triffa", region: R_ORI, province: "إقليم الناظور" },
    { id: "29 bis", name: "Saïdia du Kiss", nameAr: "سعيدية", shape: "rect", coords: p("695,71,717,97"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATjZXWTdzQmtmM28/view?usp=sharing", title: "29 bis : Saïdia du Kiss", region: R_ORI, province: "إقليم الناظور" },
    { id: "30", name: "Moulay Bou Salham", nameAr: "مولاي بوسلهام", shape: "rect", coords: p("352,108,372,133"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAUkxHV3R6eXd3TTQ/view?usp=sharing", title: "30 : Moulay Bou Salham", region: R_ORI, province: "إقليم الناظور" },
    { id: "31", name: "Lalla Mimouna", nameAr: "لالة ميمونة", shape: "rect", coords: p("373,108,394,133"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANEM3QnNBTEVuOVk/view?usp=sharing", title: "31 : Lalla Mimouna", region: R_ORI, province: "إقليم الناظور" },
    { id: "31 bis", name: "Arbaoua", nameAr: "عرباوة", shape: "rect", coords: p("394,110,412,132"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAY0U3YlMtWWRsbUE/view?usp=sharing", title: "31 bis : Arbaoua", region: R_ORI, province: "إقليم الناظور" },
    
    // Ouezzane
    { id: "32", name: "Ouezzane", nameAr: "وزان", shape: "rect", coords: p("413,109,433,132"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQnpnSkUwRWtkUEU/view?usp=sharing", title: "32 : Ouezzane", region: R_TTA, province: "إقليم وزان" },
    { id: "33", name: "Zoumi", nameAr: "زومي", shape: "rect", coords: p("434,108,454,132"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAV2lLM2VaVjlzNDQ/view?usp=sharing", title: "33 : Zoumi", region: R_TTA, province: "إقليم وزان" },
    { id: "34", name: "Beni Ahmed", nameAr: "بني أحمد", shape: "rect", coords: p("455,107,474,132"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAelRmTzBsSDNFeW8/view?usp=sharing", title: "34 : Beni Ahmed", region: R_TTA, province: "إقليم وزان" },
    { id: "35", name: "Tamorot", nameAr: "تموروت", shape: "rect", coords: p("475,107,494,131"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAU28zVS1PeVFiUFU/view?usp=sharing", title: "35 : Tamorot", region: R_TTA, province: "إقليم وزان" },

    // Oriental More
    { id: "43", name: "Hassi Berkane", nameAr: "حاسي بركان", shape: "rect", coords: p("637,101,656,124"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbjd3dE42TTdWMmM/view?usp=sharing", title: "43 : Hassi Berkane", region: R_ORI, province: "إقليم بركان" },
    { id: "43 bis", name: "Zaïo", nameAr: "زايو", shape: "rect", coords: p("657,100,676,123"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATXdQS0pHUXdiNkE/view?usp=sharing", title: "43 bis : Zaïo", region: R_ORI, province: "إقليم بركان" },
    { id: "44", name: "Berkane", nameAr: "بركان", shape: "rect", coords: p("677,99,696,122"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAdFpLVXlhZ09Dazg/view?usp=sharing", title: "44 : Berkane", region: R_ORI, province: "إقليم بركان" },
    { id: "45", name: "Ahfir", nameAr: "أحفير", shape: "rect", coords: p("696,97,717,121"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcW1tVkY4NWo0U1E/view?usp=sharing", title: "45 : Ahfir", region: R_ORI, province: "إقليم بركان" },
    { id: "46", name: "Zoudj El Berhal", nameAr: "زوج البغال", shape: "rect", coords: p("717,95,738,120"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAdTgtUHdMclFPU00/view?usp=sharing", title: "46 : Zoudj El Berhal", region: R_ORI, province: "إقليم بركان" },
    { id: "60", name: "Oujda", nameAr: "وجدة", shape: "rect", coords: p("720,121,739,145"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASnhfUHM0V2x5YlE/view?usp=sharing", title: "60 : Oujda", region: R_ORI, province: "إقليم وجدة - أنجاد" },
    { id: "73", name: "Tawrirt", nameAr: "تاوريرت", shape: "rect", coords: p("639,149,659,173"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASVVLWThOT250Zjg/view?usp=sharing", title: "73 : Tawrirt", region: R_ORI, province: "إقليم تاوريرت" },
    { id: "74", name: "Mestigmer", nameAr: "مستكمر", shape: "rect", coords: p("660,148,678,172"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAUWlIR3JBc09STXM/view?usp=sharing", title: "74 : Mestigmer", region: R_ORI, province: "إقليم تاوريرت" },
    { id: "75", name: "Metroh", nameAr: "مطروح", shape: "rect", coords: p("679,148,700,171"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAd3IxQ2dyaElVdDg/view?usp=sharing", title: "75 : Metroh", region: R_ORI, province: "إقليم تاوريرت" },
    { id: "76", name: "Jerada", nameAr: "جرادة", shape: "rect", coords: p("701,147,719,170"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANWpzazNtbUFfejg/view?usp=sharing", title: "76 : Jerada", region: R_ORI, province: "إقليم جرادة" },
    { id: "77", name: "Wad Al Himer", nameAr: "واد الحيمر", shape: "rect", coords: p("720,145,741,168"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWGhmSGV6T3FHOUE/view?usp=sharing", title: "77 : Wad Al Himer", region: R_ORI, province: "إقليم جرادة" },
    { id: "93 bis", name: "Aïn Bni Mathar", nameAr: "عين بني مطهر", shape: "rect", coords: p("701,171,721,194"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANUF4VUlGRFktLWs/view?usp=sharing", title: "93 bis : 'Ayn Bni Mathar", region: R_ORI, province: "إقليم جرادة" },
    { id: "108", name: "Debdou", nameAr: "دبدو", shape: "rect", coords: p("620,200,641,223"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQmNJSUxBM0FBNXM/view?usp=sharing", title: "108 : Debdou", region: R_ORI, province: "إقليم فكيك" },
    { id: "109", name: "Awam", nameAr: "عوام", shape: "rect", coords: p("642,198,661,222"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATTFURjYtX294UUk/view?usp=sharing", title: "109 : 'Awam", region: R_ORI, province: "إقليم فكيك" },
    { id: "110", name: "Hassyane Ad-Dyab", nameAr: "حسيان الدياب", shape: "rect", coords: p("661,196,682,221"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANTZ2Q3pFQXRxaWs/view?usp=sharing", title: "110 : Hassyane Ad-Dyab", region: R_ORI, province: "إقليم فكيك" },
    { id: "111", name: "Raçfet Al Karma", nameAr: "رصفة الكرمة", shape: "rect", coords: p("682,197,702,219"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAS3dURTJKY2dHQVU/view?usp=sharing", title: "111 : Raçfet Al Karma", region: R_ORI, province: "إقليم فكيك" },

    // Rabat-Sale-Kenitra
    { id: "61", name: "Kenitra", nameAr: "القنيطرة", shape: "rect", coords: p("333,159,354,182"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZGtSWkV0R0NqWkE/view?usp=sharing", title: "61 : Kenitra", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "62", name: "Sidi Yahia Al Gharb", nameAr: "سيدي يحيى الغرب", shape: "rect", coords: p("354,159,374,182"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAR2xTTG1xTGh3eVk/view?usp=sharing", title: "62 : Sidi Yahia Al Gharb", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "63", name: "Dar Al Gaddari", nameAr: "دار الكداري", shape: "rect", coords: p("375,159,395,182"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAdU5HdVoyQU9xOXc/view?usp=sharing", title: "63 : Dar Al Gaddari", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "64", name: "Sidi Slimane", nameAr: "سيدي سليمان", shape: "rect", coords: p("396,158,415,182"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAS2NTQkx3YXNZdVE/view?usp=sharing", title: "64 : Sidi Slimane", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "65", name: "Khenichet", nameAr: "لخنيشات", shape: "rect", coords: p("416,158,434,182"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbkp4RlBqNUszV2M/view?usp=sharing", title: "65 : Khenichet", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "65 bis", name: "Oulad Aïssa", nameAr: "أولاد عيسى", shape: "rect", coords: p("435,156,455,180"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZGZXZG5xbXMzdTA/view?usp=sharing", title: "65 bis : Oulad Aïssa", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "66", name: "Karia Ba Mohammed", nameAr: "قرية با محمد", shape: "rect", coords: p("456,156,475,180"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMlVERTgtNU1fSWM/view?usp=sharing", title: "66 : Karia Ba Mohammed", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "67", name: "Kelaa Des Sles", nameAr: "قلعة السلاس", shape: "rect", coords: p("476,156,496,178"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAckVtSnVfNGtDNHc/view?usp=sharing", title: "67 : Kelaa Des Sles", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "78", name: "Rabat", nameAr: "الرباط", shape: "rect", coords: p("313,183,334,208"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATndJSzVyX2JxcFU/view?usp=sharing", title: "78 : Rabat", region: R_RSK, province: "إقليم الرباط" },
    { id: "79", name: "Sidi Bouqnadel", nameAr: "سيدي بوقنادل", shape: "rect", coords: p("335,183,355,207"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQ3E0R1ZveTRiLW8/view?usp=sharing", title: "79 : Sidi Bouqnadel", region: R_RSK, province: "إقليم الرباط" },
    { id: "80", name: "Ma'mora", nameAr: "المعمورة", shape: "rect", coords: p("355,182,374,208"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAV3N6Z3hnb3gzVWc/view?usp=sharing", title: "80 : Ma'mora", region: R_RSK, province: "إقليم الرباط" },
    { id: "81", name: "Dar Ben Hsin", nameAr: "دار بن حسين", shape: "rect", coords: p("375,182,395,207"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAUUdSOVYtNWoyRVU/view?usp=sharing", title: "81 : Dar Ben Hsin", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "82", name: "El Kansera", nameAr: "القنصرة", shape: "rect", coords: p("396,183,415,207"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWTJpSzREN3ZjYjA/view?usp=sharing", title: "82 : El Kansera", region: R_RSK, province: "إقليم القنيطرة" },
    { id: "94", name: "Bouzniqa", nameAr: "بوزنيقة", shape: "rect", coords: p("293,208,314,232"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbjZKWU9aSjM2T1E/view?usp=sharing", title: "94 : Bouzniqa", region: R_RSK, province: "إقليم الخميسات" },
    { id: "95", name: "Temara", nameAr: "تمارة", shape: "rect", coords: p("314,208,334,232"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAX0lWaWJTel83TGc/view?usp=sharing", title: "95 : Temara", region: R_RSK, province: "إقليم الرباط" },
    { id: "96", name: "Larba't As Sehoul", nameAr: "أربعاء السهول", shape: "rect", coords: p("335,207,355,232"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANGZLdGNhY2JSWjA/view?usp=sharing", title: "96 : Larba't As Sehoul", region: R_RSK, province: "إقليم الخميسات" },
    { id: "97", name: "Tiflet", nameAr: "تيفلت", shape: "rect", coords: p("356,208,375,231"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZ3ZCYUVVb0FRaXM/view?usp=sharing", title: "97 : Tiflet", region: R_RSK, province: "إقليم الخميسات" },
    { id: "98", name: "Al Khmissat", nameAr: "الخميسات", shape: "rect", coords: p("376,208,396,231"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAT3N2bW02a1ZxeWM/view?usp=sharing", title: "98 : Al Khmissat", region: R_RSK, province: "إقليم الخميسات" },
    { id: "99", name: "Souq Larba't Wad Baht", nameAr: "سوق أربعاء واد بهت", shape: "rect", coords: p("397,207,416,230"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMktBRHVITWEwY0E/view?usp=sharing", title: "99 : Souq Larba't Wad Baht", region: R_RSK, province: "إقليم الخميسات" },

    // Fes-Meknes
    { id: "85", name: "Fes Ouest", nameAr: "فاس الغربية", shape: "rect", coords: p("457,181,476,204"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALVRESTFfdVdxdUk/view?usp=sharing", title: "85 : Fes Ouest", region: R_FM, province: "إقليم فاس" },
    { id: "86", name: "Fes Est", nameAr: "فاس الشرقية", shape: "rect", coords: p("476,179,497,204"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAOXZOMlIwcEZqY0k/view?usp=sharing", title: "86 : Fes Est", region: R_FM, province: "إقليم فاس" },
    { id: "87", name: "Matmata", nameAr: "مطماتة", shape: "rect", coords: p("498,179,518,203"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAT1YtS0VqLUZQUU0/view?usp=sharing", title: "87 : Matmata", region: R_FM, province: "إقليم فاس" },
    { id: "100", name: "Meknes", nameAr: "مكناس", shape: "rect", coords: p("417,206,436,230"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANmpSS09VQWpDSG8/view?usp=sharing", title: "100 : Meknes", region: R_FM, province: "إقليم مكناس" },
    { id: "101", name: "Seba' 'Youn", nameAr: "سبع عيون", shape: "rect", coords: p("437,206,456,229"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAVDZWV2R3WWFnLWM/view?usp=sharing", title: "101 : Seba' 'Youn", region: R_FM, province: "إقليم مكناس" },
    { id: "101 bis", name: "Aïn Taoujdat", nameAr: "عين تاوجطات", shape: "rect", coords: p("456,205,477,229"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZG85bVNWN0RSMTg/view?usp=sharing", title: "101 bis : Aïn Taoujdat", region: R_FM, province: "إقليم مكناس" },
    { id: "119", name: "Bouqachmir", nameAr: "بوقشمر", shape: "rect", coords: p("397,232,416,254"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAX182U3VrVXBKSW8/view?usp=sharing", title: "119 : Bouqachmir", region: R_FM, province: "إقليم مكناس" },
    { id: "120", name: "Agouray", nameAr: "أكوراي", shape: "rect", coords: p("417,231,436,254"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATEJteUVMUmlNR28/view?usp=sharing", title: "120 : Agouray", region: R_FM, province: "إقليم مكناس" },
    { id: "121", name: "Al Hajeb", nameAr: "الحاجب", shape: "rect", coords: p("437,231,456,254"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAYWtPX2tLWDVjNWc/view?usp=sharing", title: "121 : Al Hajeb", region: R_FM, province: "إقليم مكناس" },
    { id: "122", name: "Ifrane", nameAr: "إفران", shape: "rect", coords: p("458,231,478,252"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAa3ZidEdDU1R2VWc/view?usp=sharing", title: "122 : Ifrane", region: R_FM, province: "إقليم مكناس" },
    { id: "123", name: "Youn Snane", nameAr: "عيون سنان", shape: "rect", coords: p("479,229,499,252"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANlNhQWVaR1pOcGc/view?usp=sharing", title: "123 : 'Youn Snane", region: R_FM, province: "إقليم مكناس" },
    { id: "124", name: "Tazouta", nameAr: "تازوطة", shape: "rect", coords: p("499,230,519,251"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASnktdnhTSXA4YzA/view?usp=sharing", title: "124 : Tazouta", region: R_FM, province: "إقليم مكناس" },
    { id: "125", name: "Al Adarj", nameAr: "الأدرج", shape: "rect", coords: p("519,229,540,251"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANWMxRG1TLUpGQlU/view?usp=sharing", title: "125 : Al Adarj", region: R_FM, province: "إقليم مكناس" },
    { id: "125 bis", name: "Boulوطan", nameAr: "بولوطان", shape: "rect", coords: p("602,225,622,248"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAc0NJQmF2cVZ1MHc/view?usp=sharing", title: "125 bis : Bouloutane", region: R_FM, province: "إقليم مكناس" },
    { id: "125 ter", name: "Jebel Al Mouss", nameAr: "جبل الموس", shape: "rect", coords: p("622,223,642,247"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAOENFVFk1TllqYWs/view?usp=sharing", title: "125 ter : Jebel Al Mouss", region: R_FM, province: "إقليم مكناس" },
    { id: "141", name: "Boulmane", nameAr: "بولمان", shape: "rect", coords: p("500,253,520,276"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAX0c5V2VkbmZRWkk/view?usp=sharing", title: "141 : Boulmane", region: R_FM, province: "إقليم بولمان" },
    { id: "142", name: "Immouzer Marmoucha", nameAr: "إيموزار مرموشة", shape: "rect", coords: p("521,253,540,276"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAX25kY0FJY3d2aVE/view?usp=sharing", title: "142 : Immouzer Marmoucha", region: R_FM, province: "إقليم بولمان" },
    { id: "142 bis", name: "Outat Oulad Al Haj", nameAr: "أوطاط أولاد الحاج", shape: "rect", coords: p("581,249,602,273"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAaEpGYS0yS0dvMUU/view?usp=sharing", title: "142 bis : Outat Oulad Al Haj", region: R_FM, province: "إقليم بولمان" },
    { id: "53", name: "Taounate", nameAr: "تاونات", shape: "rect", coords: p("495,131,515,155"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcWIzSXVUYlMxTzA/view?usp=sharing", title: "53 : Taounate", region: R_FM, province: "إقليم تاونات" },
    { id: "53 bis", name: "Dhar Souk", nameAr: "ضهر السوق", shape: "rect", coords: p("516,131,536,154"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANC1hOXZySnROS3c/view?usp=sharing", title: "53 bis : Dhar Souk", region: R_FM, province: "إقليم تاونات" },
    { id: "53 ter", name: "Taïneste", nameAr: "تاينست", shape: "rect", coords: p("535,130,556,153"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMDdfTFNURmhqUzg/view?usp=sharing", title: "53 ter : Taïneste", region: R_FM, province: "إقليم تاونات" },
    { id: "54", name: "Aknoul", nameAr: "أكنول", shape: "rect", coords: p("556,129,575,151"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMWI3X21JSnlFWnM/view?usp=sharing", title: "54 : Aknoul", region: R_FM, province: "إقليم تاونات" },
    { id: "54 bis", name: "Aïn Zora", nameAr: "عين زورة", shape: "rect", coords: p("575,128,596,151"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAdVhJaUYwcUFaTW8/view?usp=sharing", title: "54 bis : Aïn Zora", region: R_FM, province: "إقليم تاونات" },
    { id: "55", name: "Saka", nameAr: "صاكة", shape: "rect", coords: p("597,128,617,150"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARTQ1Sjh6MXBFcnM/view?usp=sharing", title: "55 : Saka", region: R_FM, province: "إقليم تاونات" },
    { id: "56", name: "Melga Lwidane", nameAr: "ملتقى الويدان", shape: "rect", coords: p("618,127,637,149"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAY2RBd2o0WUg3MWM/view?usp=sharing", title: "56 : Melga Lwidane", region: R_FM, province: "إقليم تاونات" },
    { id: "57", name: "Machra' Hommadi", nameAr: "مشرع حمادي", shape: "rect", coords: p("638,124,657,149"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAalJLTWl5ZTFsVGM/view?usp=sharing", title: "57 : Machra' Hommadi", region: R_FM, province: "إقليم تاونات" },
    { id: "57 bis", name: "La'youn", nameAr: "العيون", shape: "rect", coords: p("658,124,678,147"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAeUdMMXZ1SW42akk/view?usp=sharing", title: "57 bis : La'youn", region: R_FM, province: "إقليم تاونات" },
    { id: "58", name: "Sidi Bou Houria", nameAr: "سيدي بوهرية", shape: "rect", coords: p("678,123,697,147"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAeHB6N0dCV0Z0Q1U/view?usp=sharing", title: "58 : Sidi Bou Houria", region: R_FM, province: "إقليم تاونات" },
    { id: "59", name: "Beni Oukil", nameAr: "بني وكيل", shape: "rect", coords: p("698,121,719,146"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATHdXZHJxSjlJcTg/view?usp=sharing", title: "59 : Beni Oukil", region: R_FM, province: "إقليم تاونات" },
    { id: "102", name: "Sefrou", nameAr: "صفرو", shape: "rect", coords: p("478,205,497,229"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMVp3OWo1b2VwaEk/view?usp=sharing", title: "102 : Sefrou", region: R_FM, province: "إقليم صفرو" },
    { id: "102 bis", name: "El Menzel", nameAr: "المنزل", shape: "poly", coords: p("498,203,518,203,518,228,498,228"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAejYzOTNrSnZGZUU/view?usp=sharing", title: "102 bis : El Menzel", region: R_FM, province: "إقليم صفرو" },
    { id: "103", name: "Ribat Al Khair", nameAr: "رباط الخير", shape: "rect", coords: p("519,203,538,227"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAYkt0dXo1eHpqaDQ/view?usp=sharing", title: "103 : Ribat Al Khair", region: R_FM, province: "إقليم صفرو" },
    { id: "104", name: "Maghrawa", nameAr: "مغراوة", shape: "rect", coords: p("539,202,558,226"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQUVZVUtSTkdtZE0/view?usp=sharing", title: "104 : Maghrawa", region: R_FM, province: "إقليم صفرو" },
    { id: "105", name: "Berkine", nameAr: "بركين", shape: "rect", coords: p("559,200,579,226"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAemN5Q1V4YmMtNFE/view?usp=sharing", title: "105 : Berkine", region: R_FM, province: "إقليم صفرو" },
    { id: "106", name: "Bou Rached", nameAr: "بو راشد", shape: "rect", coords: p("580,201,600,225"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcFg1V3JDT080TVk/view?usp=sharing", title: "106 : Bou Rached", region: R_FM, province: "إقليم صفرو" },
    { id: "107", name: "Mahirija", nameAr: "مهرجة", shape: "rect", coords: p("601,200,620,223"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAUVdJc3lDUWtqc2M/view?usp=sharing", title: "107 : Mahirija", region: R_FM, province: "إقليم صفرو" },

    // Beni Mellal-Khenifra
    { id: "224", name: "Beni Mellal", nameAr: "بني ملال", shape: "rect", coords: p("358,355,378,378"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMndYcTBOMzZuclk/view?usp=sharing", title: "224 : Beni Mellal", region: R_BK, province: "إقليم بني ملال" },
    { id: "225", name: "Tagzirt", nameAr: "تاكزيرت", shape: "rect", coords: p("379,354,398,377"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMUhvdEU5Q3BOTUk/view?usp=sharing", title: "225 : Tagzirt", region: R_BK, province: "إقليم بني ملال" },
    { id: "226", name: "Tizi Nisly", nameAr: "تيزي نسلي", shape: "rect", coords: p("400,354,419,377"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMlRzWDVHN3ZxMU0/view?usp=sharing", title: "226 : Tizi Nisly", region: R_BK, province: "إقليم بني ملال" },
    { id: "226 bis", name: "Aghbala", nameAr: "أغبالة", shape: "rect", coords: p("419,353,439,376"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAYWxaRnAwakxPeE0/view?usp=sharing", title: "226 bis : Aghbala", region: R_BK, province: "إقليم بني ملال" },
    { id: "249", name: "Afourar", nameAr: "أفورار", shape: "rect", coords: p("337,378,358,402"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAd19VU1JYaTdNS2c/view?usp=sharing", title: "249 : Afourar", region: R_BK, province: "إقليم بني ملال" },
    { id: "250", name: "Wawizaght", nameAr: "واويزغت", shape: "rect", coords: p("359,379,378,402"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAYzJLR2lxYnBrUDg/view?usp=sharing", title: "250 : Wawizaght", region: R_BK, province: "إقليم بني ملال" },
    { id: "251", name: "Tilougguit", nameAr: "تلوكيت", shape: "rect", coords: p("379,379,400,401"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAN0VWTmttWGo4cEU/view?usp=sharing", title: "251 : Tilougguit", region: R_BK, province: "إقليم بني ملال" },
    { id: "251 A", name: "Anergui", nameAr: "أنركي", shape: "poly", coords: p("399,377,419,377,420,401,400,402"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAd2NsMGFQSkpPV0U/view?usp=sharing", title: "251 A : Anergui", region: R_BK, province: "إقليم بني ملال" },
    { id: "251 B", name: "Imilchil", nameAr: "إملشيل", shape: "poly", coords: p("420,377,440,377,440,402,420,402"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcU5jNUdESHY1eGc/view?usp=sharing", title: "251 B : Imilchil", region: R_BK, province: "إقليم بني ملال" },
    { id: "267", name: "Tamellat", nameAr: "تملالت", shape: "rect", coords: p("256,404,275,427"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAa052bjdUcnRhTG8/view?usp=sharing", title: "267 : Tamellat", region: R_BK, province: "إقليم بني ملال" },
    { id: "179", name: "Khenifra", nameAr: "خنيفرة", shape: "rect", coords: p("419,305,438,328"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARkxjSWkwalU1SzQ/view?usp=sharing", title: "179 : Khenifra", region: R_BK, province: "إقليم خنيفرة" },
    { id: "180", name: "Karrouchan", nameAr: "كروشن", shape: "rect", coords: p("439,303,459,327"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANzNQMzl0ZlFhY1E/view?usp=sharing", title: "180 : Karrouchan", region: R_BK, province: "إقليم خنيفرة" },
    { id: "181", name: "Itzar", nameAr: "إيتزر", shape: "rect", coords: p("460,303,479,327"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbWhPTXp2REtsTnM/view?usp=sharing", title: "181 : Itzar", region: R_BK, province: "إقليم خنيفرة" },
    { id: "181 bis", name: "Aït Iloussane", nameAr: "أيت علوسان", shape: "rect", coords: p("481,303,501,327"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASUcwWFJvSDhDNFU/view?usp=sharing", title: "181 bis : Aït Iloussane", region: R_BK, province: "إقليم خنيفرة" },
    { id: "182", name: "Mibladane", nameAr: "مبلادن", shape: "rect", coords: p("501,303,520,326"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARzdrZkN4dkhoczA/view?usp=sharing", title: "182 : Mibladane", region: R_BK, province: "إقليم خنيفرة" },
    { id: "270", name: "Tanant", nameAr: "تنانت", shape: "rect", coords: p("317,403,338,427"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAS3JKQ0MzUW11cnM/view?usp=sharing", title: "270 : Tanant", region: R_BK, province: "إقليم خنيفرة" },
    { id: "271", name: "Aziylal", nameAr: "أزيلال", shape: "rect", coords: p("338,402,357,426"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASTUtOENETFRYZDQ/view?usp=sharing", title: "271 : Aziylal", region: R_BK, province: "إقليم أزيلال" },
    { id: "271 bis", name: "Aït Mhammed", nameAr: "أيت محمد", shape: "rect", coords: p("358,403,378,427"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZkJsMnBoNzVUeW8/view?usp=sharing", title: "271 bis : Aït Mhammed", region: R_BK, province: "إقليم أزيلال" },
    { id: "272", name: "Zawyat Ahançal", nameAr: "زاوية أحنصال", shape: "rect", coords: p("379,402,401,425"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARkk5cER1aUNiNXc/view?usp=sharing", title: "272 : Zawyat Ahançal", region: R_BK, province: "إقليم أزيلال" },
    { id: "288", name: "Demnat", nameAr: "دمنات", shape: "rect", coords: p("297,429,316,452"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAVVRCS3NCNEwwM28/view?usp=sharing", title: "288 : Demnat", region: R_BK, province: "إقليم أزيلال" },
    { id: "289", name: "Tifni", nameAr: "تيفني", shape: "rect", coords: p("317,428,337,451"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAYnEyYUFDZGtqSUE/view?usp=sharing", title: "289 : Tifni", region: R_BK, province: "إقليم أزيلال" },
    { id: "290", name: "Abachkou", nameAr: "أباشكو", shape: "rect", coords: p("338,428,359,452"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAeE94YXhFeWpmWDg/view?usp=sharing", title: "290 : Abachkou", region: R_BK, province: "إقليم أزيلال" },
    { id: "201", name: "Al Fqih Ben Salah", nameAr: "الفقيه بن صالح", shape: "rect", coords: p("337,331,357,354"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbXhjSW1wU2U0djA/view?usp=sharing", title: "201 : Al Fqih Ben Salah", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "202", name: "Qasbat Tadla", nameAr: "قصبة تادلة", shape: "rect", coords: p("358,330,377,353"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAazJLeTlzSjRkZmM/view?usp=sharing", title: "202 : Qasbat Tadla", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "203", name: "El Ksiba", nameAr: "القصيبة", shape: "rect", coords: p("378,329,398,353"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALWltR04yTnpWZDQ/view?usp=sharing", title: "203 : El Ksiba", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "203 bis", name: "Zawyat Ech Cheïkh", nameAr: "زاوية الشيخ", shape: "rect", coords: p("399,329,419,353"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAd3VWWWFUN3JPZk0/view?usp=sharing", title: "203 bis : Zawyat Ech Cheïkh", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "204", name: "Al Qbab", nameAr: "القباب", shape: "rect", coords: p("419,330,439,352"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAV0F5dVFselB3Sm8/view?usp=sharing", title: "204 : Al Qbab", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "205", name: "Aghbalou N Sardane", nameAr: "أغبالو ن سردان", shape: "rect", coords: p("440,329,459,351"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASno5S2o0N0I2eE0/view?usp=sharing", title: "205 : Aghbalou N Sardane", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "205 bis", name: "Boumia", nameAr: "بومية", shape: "rect", coords: p("461,329,481,351"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRATE1rRGg1SzlacFU/view?usp=sharing", title: "205 bis : Boumia", region: R_BK, province: "إقليم الفقيه بن صالح" },
    { id: "205 ter", name: "Aït Oumghar", nameAr: "أيت أومغار", shape: "rect", coords: p("481,328,502,351"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcjFod1N4SXJYbnM/view?usp=sharing", title: "205 ter : Aït Oumghar", region: R_BK, province: "إقليم الفقيه بن صالح" },

    // Casablanca-Settat
    { id: "113", name: "Casablanca", nameAr: "الدار البيضاء", shape: "rect", coords: p("253,233,272,258"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAODdqcHp6UHBlejg/view?usp=sharing", title: "113 : Casablanca", region: R_CS, province: "إقليم الدار البيضاء" },
    { id: "114", name: "Mohammedia", nameAr: "المحمدية", shape: "rect", coords: p("273,229,294,257"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQVlaZTFxMUJvZFE/view?usp=sharing", title: "114 : Mohammedia", region: R_CS, province: "إقليم الدار البيضاء" },
    { id: "128", name: "Azemmour", nameAr: "أزمور", shape: "rect", coords: p("191,257,212,282"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAaEdiWkhOQVZxeTA/view?usp=sharing", title: "128 : Azemmour", region: R_CS, province: "إقليم الجديدة" },
    { id: "129", name: "Sidi Borja", nameAr: "سيدي برجة", shape: "rect", coords: p("213,257,233,281"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAOGp0LTU4MTYxSjQ/view?usp=sharing", title: "129 : Sidi Borja", region: R_CS, province: "إقليم الجديدة" },
    { id: "130", name: "Bir Jdid", nameAr: "بير جديد", shape: "rect", coords: p("232,250,252,281"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWlFqalJHbDg3OTg/view?usp=sharing", title: "130 : Bir Jdid", region: R_CS, province: "إقليم الجديدة" },
    { id: "147", name: "El jadida", nameAr: "الجديدة", shape: "rect", coords: p("170,282,190,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAS2U5dTVvTlUydTA/view?usp=sharing", title: "147 : El jadida", region: R_CS, province: "إقليم الجديدة" },
    { id: "148", name: "Haouzia", nameAr: "الحوزية", shape: "rect", coords: p("191,282,212,307"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAX0g4SnZRb2JfTHM/view?usp=sharing", title: "148 : Haouzia", region: R_CS, province: "إقليم الجديدة" },
    { id: "149", name: "Sidi S'Id M'Achou", nameAr: "سيدي سعيد معاشو", shape: "rect", coords: p("213,283,232,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZWdDTEJuRDU3R1E/view?usp=sharing", title: "149 : Sidi S'Id M'Achou", region: R_CS, province: "إقليم الجديدة" },
    { id: "150", name: "Oulad 'Abbou", nameAr: "أولاد عبو", shape: "rect", coords: p("234,282,253,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAM3dwaC1pOWxXZHc/view?usp=sharing", title: "150 : Oulad 'Abbou", region: R_CS, province: "إقليم الجديدة" },
    { id: "168 bis", name: "Oualidia Sidi Moussa", nameAr: "الوليدية سيدي موسى", shape: "rect", coords: p("150,306,170,330"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbXJ2dFRDbVRyMnM/view?usp=sharing", title: "168 bis : Oualidia Sidi Moussa", region: R_CS, province: "إقليم الجديدة" },
    { id: "169", name: "Sidi Smail", nameAr: "سيدي سماعيل", shape: "rect", coords: p("171,307,191,330"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASTVnY0FxMl9WNms/view?usp=sharing", title: "169 : Sidi Smail", region: R_CS, province: "إقليم الجديدة" },
    { id: "151", name: "Settat", nameAr: "سطات", shape: "rect", coords: p("254,282,274,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAb3pydC1iRU9WU2s/view?usp=sharing", title: "151 : Settat", region: R_CS, province: "إقليم سطات" },
    { id: "152", name: "Ben Ahmed", nameAr: "بن أحمد", shape: "rect", coords: p("275,284,295,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAeDkzRDlIRXc3YkE/view?usp=sharing", title: "152 : Ben Ahmed", region: R_CS, province: "إقليم سطات" },
    { id: "153", name: "Mgarto", nameAr: "مكارتو", shape: "rect", coords: p("295,283,315,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAc0t5ZHQ1ZTNVWlE/view?usp=sharing", title: "153 : Mgarto", region: R_CS, province: "إقليم سطات" },
    { id: "154", name: "Tlata Gnadiz", nameAr: "ثلاثة كناديز", shape: "rect", coords: p("316,282,335,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAU1RwZmx5RHVwaXc/view?usp=sharing", title: "154 : Tlata Gnadiz", region: R_CS, province: "إقليم سطات" },
    { id: "154 bis", name: "Aït 'ammar Beni Khiran", nameAr: "أيت عمار بني خيران", shape: "rect", coords: p("335,282,356,306"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcWpNeTVhS3Zwb1U/view?usp=sharing", title: "154 bis : Aït 'ammar Beni Khiran", region: R_CS, province: "إقليم سطات" },
    { id: "155", name: "Tlat Chougrane", nameAr: "ثلاث شوكران", shape: "rect", coords: p("356,281,376,304"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALWtCWWk0b1doUE0/view?usp=sharing", title: "155 : Tlat Chougrane", region: R_CS, province: "إقليم سطات" },
    { id: "156", name: "Moulay Bou 'Azza", nameAr: "مولاي بوعزة", shape: "rect", coords: p("377,281,397,304"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbEhoaDdiMWZ6dnc/view?usp=sharing", title: "156 : Moulay Bou 'Azza", region: R_CS, province: "إقليم سطات" },
    { id: "131", name: "Barrechid", nameAr: "برشيد", shape: "rect", coords: p("253,259,273,281"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWkxRdWlSTjNBVlU/view?usp=sharing", title: "131 : Barrechid", region: R_CS, province: "إقليم برشيد" },
    { id: "132", name: "Oulad Ziane", nameAr: "أولاد زيان", shape: "rect", coords: p("274,259,294,282"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAdDJvaGJxS3c1QmM/view?usp=sharing", title: "132 : Oulاد زيان", region: R_CS, province: "إقليم برشيد" },
    { id: "133", name: "Al Gara", nameAr: "الكارة", shape: "rect", coords: p("295,258,313,282"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALUJQbUZGVEVsTHc/view?usp=sharing", title: "133 : Al Gara", region: R_CS, province: "إقليم برشيد" },
    { id: "134", name: "Sidi Zemmouri", nameAr: "سيدي الزموري", shape: "rect", coords: p("315,257,335,281"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAeUludnFySWhVdVk/view?usp=sharing", title: "134 : Sidi Zemmouri", region: R_CS, province: "إقليم برشيد" },
    { id: "115", name: "Benslimane", nameAr: "بنسليمان", shape: "rect", coords: p("294,232,314,256"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMEU2Zjl0WmhwVzQ/view?usp=sharing", title: "115 : Benslimane", region: R_CS, province: "إقليم بن سليمان" },
    { id: "116", name: "Sidi Bettach", nameAr: "سيدي بطاش", shape: "rect", coords: p("315,232,333,256"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRANU5rS1E4R2pCQWM/view?usp=sharing", title: "116 : Sidi Bettach", region: R_CS, province: "إقليم بن سليمان" },
    { id: "117", name: "Ar Rommani", nameAr: "الرماني", shape: "rect", coords: p("335,233,355,255"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZWItWEg1R0F2Skk/view?usp=sharing", title: "117 : Ar Rommani", region: R_CS, province: "إقليم بن سليمان" },
    { id: "118", name: "Tiddas", nameAr: "تيداس", shape: "rect", coords: p("355,233,375,256"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAR3BJXzBMWmV0Nms/view?usp=sharing", title: "118 : Tiddas", region: R_CS, province: "إقليم بن سليمان" },
    { id: "118 bis", name: "Sebt Aït Ikkou", nameAr: "سبت أيت إيكو", shape: "rect", coords: p("375,231,396,256"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWWdTWXp5V2ZUMGs/view?usp=sharing", title: "118 bis : Sebt Aït Ikkou", region: R_CS, province: "إقليم بن سليمان" },

    // Marrakech-Safi
    { id: "284", name: "Marrakech Gueliz", nameAr: "مراكش كيليز", shape: "rect", coords: p("214,430,233,453"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAOTJkUVc2QmFCWjQ/view?usp=sharing", title: "284 : Marrakech Gueliz", region: R_MA, province: "إقليم مراكش" },
    { id: "285", name: "Marrakech Al Madina", nameAr: "مراكش المدينة", shape: "rect", coords: p("234,429,253,453"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcXhIQUhNaVpPaDQ/view?usp=sharing", title: "285 : Marrakech Al Madina", region: R_MA, province: "إقليم مراكش" },
    { id: "286", name: "Ayt Ourir", nameAr: "أيت اورير", shape: "rect", coords: p("255,428,275,454"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWUJ3WVdST2tIalk/view?usp=sharing", title: "286 : Ayt Ourir", region: R_MA, province: "إقليم مراكش" },
    { id: "287", name: "Sidi Rahal", nameAr: "سيدي رحال", shape: "rect", coords: p("276,428,295,453"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAOXpFbGFOZDJGSEU/view?usp=sharing", title: "287 : Sidi Rahal", region: R_MA, province: "إقليم مراكش" },
    { id: "214", name: "Safi", nameAr: "أسفي", shape: "rect", coords: p("128,356,150,378"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAemJDdTdRZ01oVlU/view?usp=sharing", title: "214 : Safi", region: R_MA, province: "إقليم آسفي" },
    { id: "215", name: "Youssoufia", nameAr: "اليوسفية", shape: "rect", coords: p("171,357,192,378"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASnRleGJnQS16RGc/view?usp=sharing", title: "215 : Youssoufia", region: R_MA, province: "إقليم آسفي" },
    { id: "216", name: "Mtal", nameAr: "متال", shape: "rect", coords: p("193,357,212,379"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAVktDSWVOdHFJZm8/view?usp=sharing", title: "216 : Mtal", region: R_MA, province: "إقليم آسفي" },
    { id: "218", name: "Skhour Des Rehamna", nameAr: "صخور الرحامنة", shape: "rect", coords: p("234,357,254,378"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAc3RlMG5mSUQ1R1U/view?usp=sharing", title: "218 : Skhour Des Rehamna", region: R_MA, province: "إقليم آسفي" },
    { id: "246", name: "Qal'at Sraghna", nameAr: "قلعة السراغنة", shape: "rect", coords: p("275,380,295,403"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAM1hSSmFTaWF1b0k/view?usp=sharing", title: "246 : Qal'at Sraghna", region: R_MA, province: "إقليم قلعة السراغنة" },
    { id: "247", name: "Bezou", nameAr: "بزو", shape: "rect", coords: p("297,380,317,402"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARlpXZTFpeG1WRjQ/view?usp=sharing", title: "247 : Bezou", region: R_MA, province: "إقليم قلعة السراغنة" },
    { id: "282", name: "Chichaoua", nameAr: "شيشاوة", shape: "rect", coords: p("150,430,170,453"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMk9JamlSbTVSTGM/view?usp=sharing", title: "282 : Chichaoua", region: R_MA, province: "إقليم شيشاوة" },
    { id: "283", name: "Sidi Az Zwine", nameAr: "سيدي الزوين", shape: "rect", coords: p("192,430,213,453"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAQUc0emp2ZmlNa0U/view?usp=sharing", title: "283 : Sidi Az Zwine", region: R_MA, province: "إقليم شيشاوة" },

    // Draa-Tafilalet
    { id: "276", name: "Errachidia", nameAr: "الرشيدية", shape: "rect", coords: p("525,399,545,422"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAT2xCTlJlY0ppMm8/view?usp=sharing", title: "276 : Errachidia", region: R_DT, province: "إقليم الرشيدية" },
    { id: "277", name: "Hassi Hassane", nameAr: "حاسي حسان", shape: "rect", coords: p("568,397,587,421"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAaFJtUWd6c2hKOG8/view?usp=sharing", title: "277 : Hassi Hassane", region: R_DT, province: "إقليم الرشيدية" },
    { id: "278", name: "Boudenib", nameAr: "بودنيب", shape: "rect", coords: p("588,396,609,419"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcWlqY1dRNXRDczQ/view?usp=sharing", title: "278 : Boudenib", region: R_DT, province: "إقليم الرشيدية" },
    { id: "206", name: "Midalt", nameAr: "ميدلت", shape: "rect", coords: p("502,328,521,349"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAWXlhUy14TVA4WVE/view?usp=sharing", title: "206 : Midalt", region: R_DT, province: "إقليم ميدلت" },
    { id: "209", name: "Talsinnt", nameAr: "تالسينت", shape: "rect", coords: p("605,322,625,346"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAcy0wS3RNSjRDVm8/view?usp=sharing", title: "209 : Talsinnt", region: R_DT, province: "إقليم ميدلت" },
    { id: "322", name: "Qal'at Mgouna", nameAr: "قلعة مكونة", shape: "rect", coords: p("380,476,401,499"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMWVKOWp3TExjRHc/view?usp=sharing", title: "322 : Qal'at Mgouna", region: R_DT, province: "إقليم تنغير" },
    { id: "323", name: "Tiwit", nameAr: "تيويت", shape: "rect", coords: p("402,476,422,498"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAbG1GTGk2WHp3M0U/view?usp=sharing", title: "323 : Tiwit", region: R_DT, province: "إقليم تنغير" },
    { id: "343", name: "Ouarzazate", nameAr: "ورزازات", shape: "rect", coords: p("318,502,338,525"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAd0R2OURSV29kV0U/view?usp=sharing", title: "343 : Ouarzazate", region: R_DT, province: "إقليم ورزازات" },
    { id: "359", name: "Agdz", nameAr: "أكدز", shape: "rect", coords: p("361,527,380,548"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAa2ZCa2JXWTZ0bzg/view?usp=sharing", title: "359 : Agdz", region: R_DT, province: "إقليم ورزازات" },
    { id: "273", name: "Assoul", nameAr: "أسول", shape: "rect", coords: p("462,400,484,423"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAZGVMZExRUmp3ejg/view?usp=sharing", title: "273 : Assoul", region: R_DT, province: "إقليم زاكورة" },

    // Sous-Massa
    { id: "360", name: "Agadir", nameAr: "أكادير", shape: "rect", coords: p("86,551,107,574"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAeHRwZVhhdldDR1U/view?usp=sharing", title: "360 : Agadir", region: R_SM, province: "إقليم أكادير إداوتنان" },
    { id: "361", name: "Ghabat Admine", nameAr: "غابة أدمين", shape: "rect", coords: p("108,552,127,575"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRARjdJZzF3RTVBeUE/view?usp=sharing", title: "361 : Ghabat Admine", region: R_SM, province: "إقليم أكادير إداوتنان" },
    { id: "362", name: "Taroudannt", nameAr: "تارودانت", shape: "rect", coords: p("149,552,169,575"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAdG9BbDhualJ4WUk/view?usp=sharing", title: "362 : Taroudannt", region: R_SM, province: "إقليم تارودانت" },
    { id: "386", name: "Bou Izakarn", nameAr: "بويزكارن", shape: "rect", coords: p("85,673,105,697"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRALW11MldQekF3Slk/view?usp=sharing", title: "386 : Bou Izakarn", region: R_SM, province: "إقليم تارودانت" },
    { id: "380", name: "Tiznit", nameAr: "تيزنيت", shape: "rect", coords: p("85,624,106,648"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRAMmZIeWk3SkUxZEE/view?usp=sharing", title: "380 : Tiznit", region: R_SM, province: "إقليم تيزنيت" },
    { id: "382 bis", name: "Sidi Ifni", nameAr: "سيدي إفني", shape: "rect", coords: p("43,648,63,671"), href: "https://drive.google.com/file/d/0B_qVkuJA2pRASUJ3aTREb3VXaTA/view?usp=sharing", title: "382 bis : Sidi Ifni", region: R_SM, province: "إقليم تيزنيت" }
] as MapArea[]).sort((a, b) => {
    const parseId = (id: string) => {
        const match = id.match(/^(\d+)(.*)$/);
        if (!match) return [Infinity, id];
        return [parseInt(match[1], 10), match[2]];
    };
    const [numA, suffixA] = parseId(a.id);
    const [numB, suffixB] = parseId(b.id);
    if (numA !== numB) return (numA as number) - (numB as number);
    return (suffixA as string).localeCompare(suffixB as string);
});
